mq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
  volumes:
    - ./data/rabbitmq:/var/lib/rabbitmq
    - ./data/log:/data/log
    - ./data/mnesia:/data/mnesia
